FROM node:20.12.0-apline3.9

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

RUN db:generate

CMD [ "npm","run","start-user-app" ]