FROM node:20.8.0-alpine3.17

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

RUN cd packages/db && npx prisma generate && cd ../..

CMD [ "npm","run","start-user-app" ]